.PHONY: clean All

All:
	@echo "----------Building project:[ UOC20231 -  ]----------"
	@"$(MAKE)" -f  "UOC20231.mk"
clean:
	@echo "----------Cleaning project:[ UOC20231 -  ]----------"
	@"$(MAKE)" -f  "UOC20231.mk" clean
